SELECT MEMBERSHIPX.CLB_CD,
   MEMBERSHIPX.MBR_ID,
   MEMBERX.ASSOC_MBR_ID,
   MEMBERSHIPX.MBRS_EXPIR_DT,
   MEMBERSHIPX.MBRS_PLS_IN,
   MEMBERSHIPX.MBRS_STS_CD,
   MEMBERX.MBR_LST_NM,
      MEMBERX.MBR_FST_NM,
   MEMBERX.MBR_ID_16
   
 FROM TOKYO_INQ.MEMBERSHIPX
 
 INNER JOIN TOKYO_INQ.MEMBERX 
 ON MEMBERSHIPX.MBR_ID=MEMBERX.MBR_ID WHERE  MBRS_PLS_IN = 'N' AND MEMBERSHIPX.MBRS_STS_CD = 'C' AND rownum < 1000
   ORDER BY dbms_random.value